import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { buildStrategySpec } from "../run.mjs";

function pct(value) {
  return Number((value * 100).toFixed(4));
}

function load(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function priceMap(snapshot) {
  return new Map(snapshot.market.map((asset) => [asset.symbol, asset.priceUsd]));
}

function maxDrawdown(equityCurve) {
  let peak = equityCurve[0]?.equity ?? 1;
  let worst = 0;
  for (const point of equityCurve) {
    peak = Math.max(peak, point.equity);
    const drawdown = peak > 0 ? (point.equity - peak) / peak : 0;
    worst = Math.min(worst, drawdown);
  }
  return worst;
}

export function runBacktest(input) {
  const { snapshots, constraints } = input;
  if (!Array.isArray(snapshots) || snapshots.length < 2) {
    throw new Error("Backtest requires at least two snapshots");
  }

  let equity = 1;
  const trades = [];
  const equityCurve = [{ timestamp: snapshots[0].timestamp, equity }];

  for (let index = 0; index < snapshots.length - 1; index += 1) {
    const current = snapshots[index];
    const next = snapshots[index + 1];
    const spec = buildStrategySpec({ market: current.market, constraints });
    const selected = spec.selectedAssets.map((asset) => asset.symbol);
    const currentPrices = priceMap(current);
    const nextPrices = priceMap(next);
    const returns = selected
      .map((symbol) => {
        const start = currentPrices.get(symbol);
        const end = nextPrices.get(symbol);
        if (!start || !end) return null;
        return { symbol, returnPct: (end - start) / start };
      })
      .filter(Boolean);
    const periodReturn = returns.length
      ? returns.reduce((sum, item) => sum + item.returnPct, 0) / returns.length
      : 0;
    const turnoverCost = returns.length ? 0.0005 : 0;
    equity *= 1 + periodReturn - turnoverCost;
    trades.push({
      from: current.timestamp,
      to: next.timestamp,
      selected,
      grossReturnPct: pct(periodReturn),
      costPct: pct(turnoverCost),
      netReturnPct: pct(periodReturn - turnoverCost),
      equity: Number(equity.toFixed(6))
    });
    equityCurve.push({ timestamp: next.timestamp, equity: Number(equity.toFixed(6)) });
  }

  const winningPeriods = trades.filter((trade) => trade.netReturnPct > 0).length;
  return {
    name: "No-Signature Liquidity-Gated Momentum Skill Backtest",
    mode: "research_only_no_execution",
    walletRequired: false,
    executionAllowed: false,
    periods: trades.length,
    start: snapshots[0].timestamp,
    end: snapshots[snapshots.length - 1].timestamp,
    totalReturnPct: pct(equity - 1),
    maxDrawdownPct: pct(maxDrawdown(equityCurve)),
    hitRatePct: pct(winningPeriods / Math.max(trades.length, 1)),
    finalEquity: Number(equity.toFixed(6)),
    liquidityRejectCount: snapshots.reduce(
      (count, snapshot) => count + snapshot.market.filter((asset) => asset.volume24hUsd < constraints.minVolume24hUsd).length,
      0
    ),
    constraints,
    trades,
    equityCurve
  };
}

export function markdownReport(result) {
  const tradeRows = result.trades
    .map((trade) => `| ${trade.from.slice(0, 10)} | ${trade.to.slice(0, 10)} | ${trade.selected.join(", ")} | ${trade.netReturnPct}% | ${trade.equity} |`)
    .join("\n");
  return `# Sample Backtest Report

## Summary

- Strategy: ${result.name}
- Mode: ${result.mode}
- Wallet required: ${result.walletRequired}
- Execution allowed: ${result.executionAllowed}
- Window: ${result.start.slice(0, 10)} to ${result.end.slice(0, 10)}
- Periods: ${result.periods}
- Total return: ${result.totalReturnPct}%
- Max drawdown: ${result.maxDrawdownPct}%
- Hit rate: ${result.hitRatePct}%
- Liquidity rejects: ${result.liquidityRejectCount}

## Trades

| From | To | Selected | Net Return | Equity |
| --- | --- | --- | ---: | ---: |
${tradeRows}

## Interpretation

This is a toy sample-data backtest for submission packaging, not an investment
claim. The value is the repeatable structure: data normalization, deterministic
selection, risk gates, and reporting without live orders.

## Safety

No wallet, signature, approval, swap, bridge, perp, staking, lending, borrowing,
or transfer is generated by this backtest.
`;
}

const isCli = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];

if (isCli) {
  const inputPath = process.argv[2] ?? "data/sample-historical-snapshots.json";
  const outputPath = process.argv[3] ?? null;
  const result = runBacktest(load(inputPath));

  if (outputPath) {
    writeFileSync(outputPath, markdownReport(result));
    console.log(JSON.stringify({ wrote: outputPath, totalReturnPct: result.totalReturnPct, maxDrawdownPct: result.maxDrawdownPct }, null, 2));
  } else {
    console.log(JSON.stringify(result, null, 2));
  }
}
